### ISSUE TITLE
enforce security in App Portal to dashboard redirection

### ISSUE THREAD

**Issue by thiagomanel** [fogbow/portal-rnp-cafe#1]
Since we are going to remove the shibboleth SP from the dashboard, we need to make sure that the requests are made by the AppPortal and the content was not tampered.

**Comment by fubica** [comment]
On Jul 5, 2016, at 10:17 , Thiago Emmanuel Pereira notifications@github.com wrote:

> Since we are going to remove the shibboleth SP from the dashboard, we need to make sure that the requests are made by the AppPortal and the content was not tampered.
> 
> Actually, the request can be made by any service that is able to produce a valid token. A valid token is signed by the site admin. Therefore, a service that provides valid tokens, such as the AppPortal, needs to have access to the site admin private key (this, of course, does not need to be the site admin personal pair of pub/priv keys, but a pair of keys that the admin generates for this particular purpose).
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

---

 Francisco Vilar Brasileiro                                   VoIP:  +55 83 1075 2038
 Departamento de Sistemas e Computação   Fone:  +55 83 2101 1644
 Universidade Federal de Campina Grande   Fax:    +55 83 2101 1498
 58.429-900, Campina Grande, PB, Brasil      E-mail: fubica@dsc.ufcg.edu.br

**Comment by thiagomanel** [comment]
I talked to fubica away from keyboard; the original spec is correct, in this case we should sign with AppPortal keys.

note: after reviewing the spec, make it public available.
